Repository weaveworks/profiles, pull requests merged in 2021-05, with the labels that each got.

#98 Fix manifest namespaces and align release process with flux
  .github/workflows/release.yaml
  Makefile
  config/certmanager/certificate.yaml
  config/crd/patches/webhook_in_profilecatalogsources.yaml
  config/crd/patches/webhook_in_profiles.yaml
  config/crd/patches/webhook_in_profilesubscriptions.yaml
  config/manager/catalog_service.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prepare/kustomization.yaml
  config/prepare/manager_auth_proxy_patch.yaml
  config/prepare/manager_config_patch.yaml
  config/prepare/namespace.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
Labels: kind/improvement, skip-release-notes

#99 Remove the image editing in the Kustomization file
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: kind/bug, skip-release-notes

#105 Always generate a tagged image version instead of using latest
  .github/workflows/release.yaml
Labels: kind/improvement, skip-release-notes

#108 Multi-profile repo proposal
  docs/proposal-01-multi-profile-repo.md
Labels: kind/feature

#111 Add coverage for updating inlined values on a subscription
  README.md
  controllers/profilecatalogsource_controller.go
  tests/acceptance/acceptance_test.go
Labels: kind/improvement, skip-release-notes

#103 prevent recursive profile definitions
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
Labels: kind/feature

#112 Add catalog name and version to the subscription
  api/v1alpha1/profilesubscription_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilesubscriptions.yaml
  config/manager/kustomization.yaml
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  controllers/profilecatalogsource_controller.go
  controllers/profilecatalogsource_controller_test.go
  controllers/suite_test.go
  examples/profile-subscription-catalog-values.yaml
  main.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#118 remove profile subscription logic
  config/rbac/role.yaml
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  controllers/suite_test.go
  main.go
  pkg/git/export_test.go
  pkg/git/fakes/fake_http_client.go
  pkg/git/git.go
  pkg/git/git_suite_test.go
  pkg/git/git_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/export_test.go
  pkg/profile/git_repo.go
  pkg/profile/git_repo_test.go
  pkg/profile/helm.go
  pkg/profile/helm_test.go
  pkg/profile/kustomize.go
  pkg/profile/kustomize_test.go
  pkg/profile/profile.go
  pkg/profile/profile_suite_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature, kind/improvement

#120 Fix the architecture of the docker build
  Dockerfile
Labels: kind/bug

#121 add 0.0.2 release notes
  docs/release_notes/v0.0.2.md
Labels: skip-release-notes

#126 Add support for querying for latest version in catalog
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#131 add v0.0.3 notes
  docs/release_notes/v0.0.3.md
Labels: skip-release-notes

#132 Only gather versions for profileName when version is "latest"
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
Labels: kind/bug

#128 Update docs
  README.md
Labels: skip-release-notes
