Repository weaveworks/profiles, pull requests merged in 2021-06, with the labels that each got.

#134 Match version field to regex
  api/v1alpha1/profilecatalogsource_types.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#133 Added GreaterThan version update check to catalog api
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#141 add v0.0.4 notes
  docs/release_notes/v0.0.4.md
Labels: kind/feature

#146 check query params in API calls and update missing tests
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
Labels: kind/bug

#151 add logging
  controllers/profilecatalogsource_controller.go
  main.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
Labels: kind/feature, kind/improvement

#152 Fix api version
  docs/proposal-01-multi-profile-repo.md
Labels: skip-release-notes

#154 Adding release doc
  docs/release_notes/v0.0.5.md
Labels: skip-release-notes

#155 add new tag field
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/profilesubscription_types.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  config/crd/bases/weave.works_profilesubscriptions.yaml
  docs/release_notes/v0.0.6.md
  examples/profile-catalog-source.yaml
Labels: skip-release-notes

#157 refactor CRDs
  api/v1alpha1/profile_types.go
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/profileinstallation_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  config/crd/bases/weave.works_profiledefinitions.yaml
  config/crd/bases/weave.works_profileinstallations.yaml
  config/crd/bases/weave.works_profiles.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_profileinstallations.yaml
  config/crd/patches/webhook_in_profileinstallations.yaml
  config/rbac/profileinstallation_editor_role.yaml
  config/rbac/profileinstallation_viewer_role.yaml
  controllers/profilecatalogsource_controller_test.go
  docs/release_notes/v0.0.7.md
  examples/profile-catalog-source.yaml
  examples/profile-subscription-catalog-values.yaml
  examples/profile-subscription-configmap.yaml
  examples/profile-subscription-values-from.yaml
  examples/profile-subscription-values.yaml
  examples/profile-subscription.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature, kind/improvement

#158 remove unused func
  api/v1alpha1/profile_types.go
Labels: skip-release-notes

#166 Bump deps
  .github/workflows/acceptance.yaml
  .github/workflows/test.yaml
  go.mod
  go.sum
Labels: area/build-and-release, skip-release-notes

#163 Add DefaultValues field for authors
  Makefile
  api/v1alpha1/profile_types.go
  api/v1alpha1/profileinstallation_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profiledefinitions.yaml
  config/crd/bases/weave.works_profileinstallations.yaml
Labels: kind/feature

#168 add notes for 008
  docs/release_notes/v0.0.8.md
Labels: skip-release-notes

#139 Create a dev tag on creating branches
  .github/workflows/create-tag.yaml
  README.md
Labels: kind/feature

#174 bump deps
  go.mod
  go.sum
Labels: skip-release-notes

#164 Show all catalog entries
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
Labels: kind/feature

#180 Release v0.0.9
  docs/release_notes/v0.0.9.md
Labels: kind/feature

#181 add support for configmap during installation
  api/v1alpha1/profileinstallation_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profileinstallations.yaml
Labels: kind/improvement, skip-release-notes

#182 add v0.0.10 release
  docs/release_notes/v0.0.10.md
Labels: skip-release-notes

#162 add support for scanning repositories for profiles
  .github/workflows/acceptance.yaml
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  config/rbac/role.yaml
  controllers/profilecatalogsource_controller.go
  examples/profile-catalog-source.yaml
  go.mod
  go.sum
  pkg/api/api.go
  pkg/git/git.go
  pkg/gitrepository/fakes/fake_kubernetes.go
  pkg/gitrepository/gitrepository_suite_test.go
  pkg/gitrepository/manager.go
  pkg/gitrepository/manager_test.go
  pkg/scanner/fakes/fake_git_client.go
  pkg/scanner/fakes/fake_http_client.go
  pkg/scanner/fakes/fake_repo_manager.go
  pkg/scanner/scanner.go
  pkg/scanner/scanner_suite_test.go
  pkg/scanner/scanner_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#187 Fix the pr label checker
  .github/workflows/pr-labels.yaml
Labels: kind/bug, skip-release-notes

#188 Bootstrap docs
  userdocs/profiles.dev/.gitignore
  userdocs/profiles.dev/README.md
  userdocs/profiles.dev/babel.config.js
  userdocs/profiles.dev/blog/2021-06-21-hello-world.md
  userdocs/profiles.dev/docs/advanced/_category_.json
  userdocs/profiles.dev/docs/advanced/advanced.md
  userdocs/profiles.dev/docs/author-docs/_category_.json
  userdocs/profiles.dev/docs/author-docs/simple-profile.md
  userdocs/profiles.dev/docs/catalog-docs/_category_.json
  userdocs/profiles.dev/docs/catalog-docs/simple-catalog.md
  userdocs/profiles.dev/docs/community.md
  userdocs/profiles.dev/docs/contributing.md
  userdocs/profiles.dev/docs/faq.md
  userdocs/profiles.dev/docs/installer-docs/_category_.json
  userdocs/profiles.dev/docs/installer-docs/simple-install.md
  userdocs/profiles.dev/docs/intro.md
  userdocs/profiles.dev/docs/pctl/_category_.json
  userdocs/profiles.dev/docs/pctl/cheat-sheet.md
  userdocs/profiles.dev/docs/tutorial-basics/_category_.json
  userdocs/profiles.dev/docs/tutorial-basics/installation.md
  userdocs/profiles.dev/docusaurus.config.js
  userdocs/profiles.dev/package.json
  userdocs/profiles.dev/sidebars.js
  userdocs/profiles.dev/src/components/HomepageFeatures.js
  userdocs/profiles.dev/src/components/HomepageFeatures.module.css
  userdocs/profiles.dev/src/css/custom.css
  userdocs/profiles.dev/src/pages/index.js
  userdocs/profiles.dev/src/pages/index.module.css
  userdocs/profiles.dev/src/pages/markdown-page.md
  userdocs/profiles.dev/static/.nojekyll
  userdocs/profiles.dev/static/img/docusaurus.png
  userdocs/profiles.dev/static/img/favicon.ico
  userdocs/profiles.dev/static/img/logo.svg
  userdocs/profiles.dev/static/img/tutorial/docsVersionDropdown.png
  userdocs/profiles.dev/static/img/tutorial/localeDropdown.png
  userdocs/profiles.dev/static/img/undraw_docusaurus_mountain.svg
  userdocs/profiles.dev/static/img/undraw_docusaurus_react.svg
  userdocs/profiles.dev/static/img/undraw_docusaurus_tree.svg
  userdocs/profiles.dev/yarn.lock
Labels: kind/docs, skip-release-notes

#184 Switch to grpc-gateway on the manager and add graceful shutdown support for all services
  .golangci.yml
  Makefile
  README.md
  api/v1alpha1/profilecatalogsource_types.go
  buf.gen.yaml
  buf.lock
  buf.yaml
  config/crd/bases/weave.works_profilecatalogsources.yaml
  docs/index.html
  go.mod
  go.sum
  main.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/catalog/catalog.go
  pkg/gateway/server.go
  pkg/grpc/server.go
  pkg/interrupt/handler.go
  pkg/manager/server.go
  pkg/protos/profiles.pb.go
  pkg/protos/profiles.pb.gw.go
  pkg/protos/profiles_grpc.pb.go
  pkg/protos/response.go
  pkg/protos/transform.go
  proto/profiles.proto
  tests/acceptance/acceptance_test.go
  tools/tools.go
Labels: kind/feature

#189 Release v0.0.11
  docs/release_notes/v0.0.11.md
Labels: skip-release-notes

#185 only re-scan new tags
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  controllers/export_test.go
  controllers/profilecatalogsource_controller.go
  controllers/profilecatalogsource_controller_test.go
  controllers/suite_test.go
  examples/profile-catalog-source-manual-list.yaml
  examples/profile-catalog-source.yaml
  main.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/scanner/fakes/fake_scanner.go
  pkg/scanner/scanner.go
  pkg/scanner/scanner_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature, kind/improvement
