Repository weaveworks/profiles, pull requests merged in 2021-07, with the labels that each got.

#195 Docs: intro and basic tutorial
  .github/workflows/acceptance.yaml
  userdocs/profiles.dev/README.md
  userdocs/profiles.dev/docs/community.md
  userdocs/profiles.dev/docs/contributing.md
  userdocs/profiles.dev/docs/faq.md
  userdocs/profiles.dev/docs/intro.md
  userdocs/profiles.dev/docs/troubleshooting.md
  userdocs/profiles.dev/docs/tutorial-basics/create-a-profile.md
  userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md
  userdocs/profiles.dev/docs/tutorial-basics/installation.md
  userdocs/profiles.dev/docs/tutorial-basics/setup.md
  userdocs/profiles.dev/docusaurus.config.js
  userdocs/profiles.dev/src/pages/index.js
Labels: kind/docs, skip-release-notes

#201 Bump all the deps
  README.md
  go.mod
  go.sum
Labels: skip-release-notes

#202 setup weaveworks.github.io/profiles/ for docs
  userdocs/profiles.dev/docusaurus.config.js
Labels: skip-release-notes

#204 setup workflow for deploying docs
  .github/workflows/deploy-docs.yaml
  Makefile
Labels: kind/docs

#212 remove failing create tag workflow
  .github/workflows/create-tag.yaml
Labels: skip-release-notes

#211 bump deps
  go.mod
  go.sum
Labels: dependencies, skip-release-notes

#213 deploy docs on changes to main
  .github/workflows/deploy-docs.yaml
Labels: skip-release-notes

#200 Add detailed author docs
  .github/workflows/acceptance.yaml
  userdocs/profiles.dev/docs/author-docs/default-values.md
  userdocs/profiles.dev/docs/author-docs/kustomize-and-raw.md
  userdocs/profiles.dev/docs/author-docs/local-helm-chart.md
  userdocs/profiles.dev/docs/author-docs/nested-profiles.md
  userdocs/profiles.dev/docs/author-docs/profile-definition-schema.md
  userdocs/profiles.dev/docs/author-docs/profile-structure.md
  userdocs/profiles.dev/docs/author-docs/remote-helm-chart.md
  userdocs/profiles.dev/docs/author-docs/simple-profile.md
  userdocs/profiles.dev/docs/author-docs/versioning.md
  userdocs/profiles.dev/docusaurus.config.js
Labels: kind/docs, skip-release-notes

#203 Use profiles.dev instead of weaveworks.github.io/profiles/
  userdocs/profiles.dev/docusaurus.config.js
Labels: kind/docs

#218 yarn upgrade --latest
  userdocs/profiles.dev/package.json
  userdocs/profiles.dev/yarn.lock
Labels: skip-release-notes

#216 use PROFILES_DOCS_WEAVEWORKS_DOCS_BOT_DEPLOY_KEY key in deploy docs
  .github/workflows/deploy-docs.yaml
Labels: skip-release-notes

#221 cd into docs directory when deploying
  .github/workflows/deploy-docs.yaml
Labels: skip-release-notes

#219 add yarn to dependabot
  .github/dependabot.yml
Labels: skip-release-notes

#205 Remove spec.Name from profile definition
  api/v1alpha1/profile_types.go
  api/v1alpha1/profilecatalogsource_types.go
  config/crd/bases/weave.works_profiledefinitions.yaml
  controllers/profilecatalogsource_controller_test.go
  pkg/api/api_test.go
  pkg/catalog/catalog_test.go
  pkg/protos/transform.go
  pkg/scanner/scanner.go
  pkg/scanner/scanner_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/improvement

#223 add 1.12 notes
  docs/release_notes/v0.0.12.md
Labels: skip-release-notes

#224 gh-pages: add CNAME
  userdocs/profiles.dev/static/CNAME
Labels: skip-release-notes

#220 Add detailed installer docs
  userdocs/profiles.dev/docs/advanced/_category_.json
  userdocs/profiles.dev/docs/advanced/advanced.md
  userdocs/profiles.dev/docs/author-docs/kustomize-and-raw.md
  userdocs/profiles.dev/docs/author-docs/local-helm-chart.md
  userdocs/profiles.dev/docs/author-docs/profile-structure.md
  userdocs/profiles.dev/docs/installer-docs/generate-local-manifests.md
  userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
  userdocs/profiles.dev/docs/installer-docs/listing-installed-profiles.md
  userdocs/profiles.dev/docs/installer-docs/removing-profiles.md
  userdocs/profiles.dev/docs/installer-docs/setting-values.md
  userdocs/profiles.dev/docs/installer-docs/simple-install.md
  userdocs/profiles.dev/docs/installer-docs/using-catalogs.md
  userdocs/profiles.dev/docs/intro.md
  userdocs/profiles.dev/docs/pctl/cheat-sheet.md
  userdocs/profiles.dev/docs/pctl/install.md
  userdocs/profiles.dev/docs/pctl/list.md
  userdocs/profiles.dev/docs/pctl/prepare.md
  userdocs/profiles.dev/docs/pctl/search.md
  userdocs/profiles.dev/docs/pctl/show.md
  userdocs/profiles.dev/docs/troubleshooting.md
  userdocs/profiles.dev/docs/tutorial-basics/setup.md
  userdocs/profiles.dev/docusaurus.config.js
Labels: kind/docs, skip-release-notes

#228 Autogenerate pctl commands in docs
  .github/workflows/build-docs.yaml
  .github/workflows/deploy-docs.yaml
  .gitignore
  Makefile
  userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
  userdocs/profiles.dev/docs/pctl/_category_.json
  userdocs/profiles.dev/docs/pctl/install.md
  userdocs/profiles.dev/docs/pctl/list.md
  userdocs/profiles.dev/docs/pctl/prepare.md
  userdocs/profiles.dev/docs/pctl/search.md
  userdocs/profiles.dev/docs/pctl/show.md
Labels: kind/docs, skip-release-notes

#226 Add catalog manager docs
  userdocs/profiles.dev/docs/catalog-docs/add-profiles.md
  userdocs/profiles.dev/docs/catalog-docs/catalog-source-schema.md
  userdocs/profiles.dev/docs/catalog-docs/simple-catalog.md
  userdocs/profiles.dev/docusaurus.config.js
Labels: kind/docs, skip-release-notes

#230 Adding dependsOn field to the artifacts
  api/v1alpha1/profile_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profiledefinitions.yaml
  docs/release_notes/v0.0.13.md
  main.go
Labels: kind/feature

#247 add gitrepository details to profile-installation file
  api/v1alpha1/profileinstallation_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profileinstallations.yaml
Labels: kind/improvement

#248 add v0.1.0 release notes
  docs/release_notes/v0.1.0.md
Labels: skip-release-notes

#250 populate release with contents of release notes file
  .github/workflows/release.yaml
Labels: skip-release-notes

#233 Profiles dev documentation theme updates
  userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
  userdocs/profiles.dev/docs/intro.md
  userdocs/profiles.dev/docs/tutorial-basics/setup.md
  userdocs/profiles.dev/docusaurus.config.js
  userdocs/profiles.dev/src/components/HomepageFeatures.js
  userdocs/profiles.dev/src/css/custom.css
  userdocs/profiles.dev/src/pages/index.js
  userdocs/profiles.dev/src/pages/index.module.css
  userdocs/profiles.dev/static/img/favicon_150px.png
  userdocs/profiles.dev/static/img/weave-logo.png
Labels: kind/docs, skip-release-notes

#251 add setting of service type to clusterIP in example doc
  userdocs/profiles.dev/docs/tutorial-basics/create-a-profile.md
Labels: kind/improvement

#253 Add dependsOn explanation
  userdocs/profiles.dev/docs/author-docs/dependencies.md
  userdocs/profiles.dev/docs/author-docs/kustomize-and-raw.md
  userdocs/profiles.dev/docs/author-docs/local-helm-chart.md
  userdocs/profiles.dev/docs/author-docs/profile-definition-schema.md
  userdocs/profiles.dev/docs/author-docs/profile-structure.md
  userdocs/profiles.dev/docs/author-docs/versioning.md
  userdocs/profiles.dev/docs/installer-docs/generate-local-manifests.md
  userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
  userdocs/profiles.dev/docs/installer-docs/setting-values.md
  userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md
Labels: kind/docs, skip-release-notes

#256 Update docs for nested dependencies
  userdocs/profiles.dev/docs/author-docs/dependencies.md
Labels: skip-release-notes

#252 add upgrade docs
  userdocs/profiles.dev/docs/installer-docs/listing-installed-profiles.md
  userdocs/profiles.dev/docs/installer-docs/upgrading-profiles.md
Labels: skip-release-notes

#255 Rename `pctl install` to `pctl add`
  README.md
  userdocs/profiles.dev/docs/faq.md
  userdocs/profiles.dev/docs/installer-docs/generate-local-manifests.md
  userdocs/profiles.dev/docs/installer-docs/installing-via-gitops.md
  userdocs/profiles.dev/docs/installer-docs/setting-values.md
  userdocs/profiles.dev/docs/installer-docs/using-catalogs.md
  userdocs/profiles.dev/docs/intro.md
  userdocs/profiles.dev/docs/troubleshooting.md
  userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md
Labels: kind/docs

#258 Update docs with more info about `defaultValues`
  userdocs/profiles.dev/docs/tutorial-basics/create-a-profile.md
Labels: kind/docs, skip-release-notes

#260 Fix small `kubectl` typo
  userdocs/profiles.dev/docs/tutorial-basics/install-a-profile.md
Labels: kind/docs, skip-release-notes
