Repository weaveworks/profiles, pull requests merged in 2021-04, with the labels that each got.

#38 Add license
  LICENSE
Labels: skip-release-notes

#39 Switch context if kind cluster exists
  hack/load-kind.sh
Labels: skip-release-notes

#28 Support passing values to HelmReleases
  api/v1alpha1/profilesubscription_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilesubscriptions.yaml
  controllers/profile_controller_test.go
  examples/profile-subscription-configmap.yaml
  examples/profile-subscription-values-from.yaml
  examples/profile-subscription-values.yaml
  go.mod
  go.sum
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
Labels: kind/feature

#34 Add catalog support
  Makefile
  PROJECT
  README.md
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_profilecatalogsources.yaml
  config/crd/patches/webhook_in_profilecatalogsources.yaml
  config/rbac/profilecatalogsource_editor_role.yaml
  config/rbac/profilecatalogsource_viewer_role.yaml
  config/rbac/role.yaml
  controllers/profilecatalogsource_controller.go
  controllers/profilecatalogsource_controller_test.go
  controllers/suite_test.go
  examples/profile-catalog-source.yaml
  go.mod
  go.sum
  main.go
  pkg/api/api.go
  pkg/api/api_suite_test.go
  pkg/api/api_test.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_suite_test.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#37 add support for raw yaml artifacts
  Makefile
  api/v1alpha1/profile_types.go
  config/crd/bases/weave.works_profiledefinitions.yaml
  config/rbac/role.yaml
  controllers/profile_controller.go
  go.mod
  go.sum
  main.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  tests/acceptance/acceptance_suite_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#47 Fixing the linter to show more errors and do more checks
  .golangci.yml
  Makefile
  main.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/profile/artifact_test.go
  pkg/profile/profile.go
  tests/acceptance/acceptance_suite_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/bug

#46 Add get endpoint to catalog url
  README.md
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  controllers/profilecatalogsource_controller.go
  controllers/profilecatalogsource_controller_test.go
  controllers/suite_test.go
  examples/profile-catalog-source.yaml
  main.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#48 Update profile subscription resource status to show artifact resource state
  Makefile
  api/v1alpha1/profilesubscription_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilesubscriptions.yaml
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  controllers/suite_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
Labels: kind/feature

#61 Add support for multiple artifacts
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#54 Add ability to access helm charts through a provided Helm URL
  Makefile
  api/v1alpha1/profile_types.go
  api/v1alpha1/profilecatalogsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  config/crd/bases/weave.works_profiledefinitions.yaml
  config/rbac/role.yaml
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  go.mod
  go.sum
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
Labels: kind/feature

#73 Update example with correct pctl command
  README.md
Labels: skip-release-notes

#75 reconcile artifact resources
  controllers/profile_controller.go
  controllers/profile_controller_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/git_repo.go
  pkg/profile/git_repo_test.go
  pkg/profile/helm.go
  pkg/profile/helm_test.go
  pkg/profile/kustomize.go
  pkg/profile/kustomize_test.go
  pkg/profile/profile.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#79 Add initial docs and some diagrams
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  README.md
  api/v1alpha1/profilecatalogsource_types.go
  config/crd/bases/weave.works_profilecatalogsources.yaml
  controllers/profilecatalogsource_controller_test.go
  docs/assets/catalog.jpg
  docs/assets/pctl_install.png
  docs/assets/pctl_install_ladder.png
  docs/assets/psub_install.png
  examples/profile-catalog-source.yaml
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/docs

#65 Keep in-memory cache synchronized with ProfileCatalogSource
  Makefile
  controllers/profilecatalogsource_controller.go
  controllers/profilecatalogsource_controller_test.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/fakes/fake_catalog.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  tests/acceptance/acceptance_test.go
Labels: kind/feature

#86 remove pctl port-forwarding docs
  README.md
Labels: skip-release-notes

#23 Add release actions
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  README.md
  docs/release_notes/0.0.1.md
Labels: skip-release-notes

#90 Fixed the usage of VERSION
  .github/workflows/release.yaml
Labels: kind/bug, skip-release-notes

#78 Add support for nested profiles
  api/v1alpha1/profile_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/weave.works_profiledefinitions.yaml
  controllers/profile_controller_test.go
  pkg/profile/artifact.go
  pkg/profile/artifact_test.go
  pkg/profile/export_test.go
  pkg/profile/profile.go
Labels: kind/feature

#91 Changing back the username for the docker login event
  .github/workflows/release.yaml
Labels: kind/bug, skip-release-notes

#92 Update Readme
  README.md
Labels: skip-release-notes

#93 remove branch name from helmrepo name
  controllers/profile_controller_test.go
  pkg/profile/artifact_test.go
  pkg/profile/helm.go
Labels: kind/improvement, skip-release-notes

#94 Changing secrets to use the organization secret for the docker user
  .github/workflows/release.yaml
Labels: kind/improvement, skip-release-notes

#95 Adding tar-ing up the manifest files.
  .github/workflows/release.yaml
Labels: area/build-and-release, skip-release-notes
